name: Fintech CAA CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "jaynilsoni/caa_fintech-angular_event_manager"

jobs:
  CI:
    runs-on: self-hosted

    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Checkout deployment files repo
        uses: actions/checkout@v4
        with:
          repository: JAYNILSONI/Kubernetes_Deployment_Files
          token: ${{ secrets.DEPLOYMENTFILES_PAT }}
          path: deploymentfiles

      - name: Set short SHA
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV 
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Dependency Installation
        run: npm ci
        # npm install jsencrypt@3.0.0-rc.1

      - name: Angular SetUp
        run: npm install -g @angular/cli

      - name: Build Dependency
        run: NODE_OPTIONS=--openssl-legacy-provider ng build --configuration=production
      
      - name: Zip dist folder
        run: zip -r dist.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist-zip
          path: dist.zip

      - name: GitHub Container Registry Authentication
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBPACKAGETOKEN }}

      - name: Docker Buildx SetUp
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
      
      - name: Trivy Scan
        run: |
          trivy image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }} \
            | tee caa_${{ env.SHORT_SHA }}.txt
        working-directory: deploymentfiles/bashScript

      - name: Count vulnerabilities
        run: |
          echo "Count Critical and High Alerts of the docker image..."
          chmod +x trivy_image_counter.bash
          ./trivy_image_counter.bash caa_${{ env.SHORT_SHA }}.txt
        working-directory: deploymentfiles/bashScript

      - name: CycloneDX SetUp
        run: |
          npm install @cyclonedx/bom --save-dev -y
          npx cyclonedx-bom -o bom.json
      
      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          protocol: ${{ secrets.DEPENDENCYTRACK_PROTOCOL }}
          port: ${{ secrets.DEPENDENCYTRACK_PORT }}
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          project: ${{ secrets.DEPENDENCYTRACK_PROJECT_ID }}
          bomFilename: "bom.json"
          autoCreate: false

      - name: Update Manifest
        run: | 
          echo "ci manifest update"
          chmod +x ./bashScript/tag_update.bash
          ./bashScript/tag_update.bash master deployment ${{ env.SHORT_SHA }} dev fintech-caa

          git config user.name "CI Bot"
          git config user.email "ci@jaynilsoni.dev"
          git add manifest/fintech-caa/deployment.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }} for caa"
          git push origin dev
        working-directory: deploymentfiles
      