name: Fintech CAA CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "caa_fintech-angular_event_manager"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Dependency Installation
        run: |
          npm install jsencrypt@3.0.0-rc.1
          npm ci

      - name: Angular SetUp
        run: npm install -g @angular/cli

      - name: Build Dependency
        run: NODE_OPTIONS=--openssl-legacy-provider ng build --configuration=production
      
      - name: Zip dist folder
        run: zip -r dist.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist-zip
          path: dist.zip

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.18.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
