name: Fintech CAA CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Dependency Installation
        run: |
          npm install jsencrypt@3.0.0-rc.1
          npm install

      - name: Angular SetUp
        run: npm install -g @angular/cli
        
      - name: Set Node.js legacy OpenSSL flag
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Build Dependency
        run: ng build
